# Generated by Django 5.0.6 on 2024-06-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
