# Generated by Django 5.0.6 on 2024-06-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsPage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
